module.exports = {
  env: {
    POLIS_APP_ID: process.env.POLIS_APP_ID,
    POLIS_REDIRECT_URL: process.env.POLIS_REDIRECT_URL,
    STARLEDGER_ACCOUNT_ADDRESS: process.env.STARLEDGER_ACCOUNT_ADDRESS,
    STARLEDGER_CONTRACT_ADDRESS: process.env.STARLEDGER_CONTRACT_ADDRESS,
    STARLEDGER_MAP_URL: process.env.STARLEDGER_MAP_URL,
  },
};
